// Code generated by "enumer -type=PhysicalIo physicalio.go"; DO NOT EDIT.

package pinout

import (
	"fmt"
	"strings"
)

const _PhysicalIoName = "UnknownPhysicalIoDebugLedEnDashboardEnHvilLedEnBrakeLightEnStatusLedEnRtdsEnAccelPedalPosition1AccelPedalPosition2BrakePedalPosition1BrakePedalPosition2SuspensionTravel1SuspensionTravel2SteeringAngleStartButtonNWheelSpeedLeftAWheelSpeedLeftBWheelSpeedRightAWheelSpeedRightBMotorControllerPrechargeEnInverterEnAccumulatorEnShutdownCircuitEnTsalEnRaspiEnFrontControllerEnSpeedgoatEnMotorControllerEnImuGpsEnDcdcValidDcdcEnDcdcEnLedPowerTrainPumpEnPowertrainFanEnHvCurrentSenseLvController3v3RefVoltageFrontController3v3RefVoltageHvilDisableHvilFeedbackGlvmsDisableIndicatorLedIndicatorButton"

var _PhysicalIoIndex = [...]uint16{0, 17, 27, 38, 47, 59, 70, 76, 95, 114, 133, 152, 169, 186, 199, 211, 226, 241, 257, 273, 299, 309, 322, 339, 345, 352, 369, 380, 397, 405, 414, 420, 429, 445, 460, 474, 499, 527, 538, 550, 562, 574, 589}

const _PhysicalIoLowerName = "unknownphysicaliodebugledendashboardenhvilledenbrakelightenstatusledenrtdsenaccelpedalposition1accelpedalposition2brakepedalposition1brakepedalposition2suspensiontravel1suspensiontravel2steeringanglestartbuttonnwheelspeedleftawheelspeedleftbwheelspeedrightawheelspeedrightbmotorcontrollerprechargeeninverterenaccumulatorenshutdowncircuitentsalenraspienfrontcontrollerenspeedgoatenmotorcontrollerenimugpsendcdcvaliddcdcendcdcenledpowertrainpumpenpowertrainfanenhvcurrentsenselvcontroller3v3refvoltagefrontcontroller3v3refvoltagehvildisablehvilfeedbackglvmsdisableindicatorledindicatorbutton"

func (i PhysicalIo) String() string {
	if i < 0 || i >= PhysicalIo(len(_PhysicalIoIndex)-1) {
		return fmt.Sprintf("PhysicalIo(%d)", i)
	}
	return _PhysicalIoName[_PhysicalIoIndex[i]:_PhysicalIoIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PhysicalIoNoOp() {
	var x [1]struct{}
	_ = x[UnknownPhysicalIo-(0)]
	_ = x[DebugLedEn-(1)]
	_ = x[DashboardEn-(2)]
	_ = x[HvilLedEn-(3)]
	_ = x[BrakeLightEn-(4)]
	_ = x[StatusLedEn-(5)]
	_ = x[RtdsEn-(6)]
	_ = x[AccelPedalPosition1-(7)]
	_ = x[AccelPedalPosition2-(8)]
	_ = x[BrakePedalPosition1-(9)]
	_ = x[BrakePedalPosition2-(10)]
	_ = x[SuspensionTravel1-(11)]
	_ = x[SuspensionTravel2-(12)]
	_ = x[SteeringAngle-(13)]
	_ = x[StartButtonN-(14)]
	_ = x[WheelSpeedLeftA-(15)]
	_ = x[WheelSpeedLeftB-(16)]
	_ = x[WheelSpeedRightA-(17)]
	_ = x[WheelSpeedRightB-(18)]
	_ = x[MotorControllerPrechargeEn-(19)]
	_ = x[InverterEn-(20)]
	_ = x[AccumulatorEn-(21)]
	_ = x[ShutdownCircuitEn-(22)]
	_ = x[TsalEn-(23)]
	_ = x[RaspiEn-(24)]
	_ = x[FrontControllerEn-(25)]
	_ = x[SpeedgoatEn-(26)]
	_ = x[MotorControllerEn-(27)]
	_ = x[ImuGpsEn-(28)]
	_ = x[DcdcValid-(29)]
	_ = x[DcdcEn-(30)]
	_ = x[DcdcEnLed-(31)]
	_ = x[PowerTrainPumpEn-(32)]
	_ = x[PowertrainFanEn-(33)]
	_ = x[HvCurrentSense-(34)]
	_ = x[LvController3v3RefVoltage-(35)]
	_ = x[FrontController3v3RefVoltage-(36)]
	_ = x[HvilDisable-(37)]
	_ = x[HvilFeedback-(38)]
	_ = x[GlvmsDisable-(39)]
	_ = x[IndicatorLed-(40)]
	_ = x[IndicatorButton-(41)]
}

var _PhysicalIoValues = []PhysicalIo{UnknownPhysicalIo, DebugLedEn, DashboardEn, HvilLedEn, BrakeLightEn, StatusLedEn, RtdsEn, AccelPedalPosition1, AccelPedalPosition2, BrakePedalPosition1, BrakePedalPosition2, SuspensionTravel1, SuspensionTravel2, SteeringAngle, StartButtonN, WheelSpeedLeftA, WheelSpeedLeftB, WheelSpeedRightA, WheelSpeedRightB, MotorControllerPrechargeEn, InverterEn, AccumulatorEn, ShutdownCircuitEn, TsalEn, RaspiEn, FrontControllerEn, SpeedgoatEn, MotorControllerEn, ImuGpsEn, DcdcValid, DcdcEn, DcdcEnLed, PowerTrainPumpEn, PowertrainFanEn, HvCurrentSense, LvController3v3RefVoltage, FrontController3v3RefVoltage, HvilDisable, HvilFeedback, GlvmsDisable, IndicatorLed, IndicatorButton}

var _PhysicalIoNameToValueMap = map[string]PhysicalIo{
	_PhysicalIoName[0:17]:         UnknownPhysicalIo,
	_PhysicalIoLowerName[0:17]:    UnknownPhysicalIo,
	_PhysicalIoName[17:27]:        DebugLedEn,
	_PhysicalIoLowerName[17:27]:   DebugLedEn,
	_PhysicalIoName[27:38]:        DashboardEn,
	_PhysicalIoLowerName[27:38]:   DashboardEn,
	_PhysicalIoName[38:47]:        HvilLedEn,
	_PhysicalIoLowerName[38:47]:   HvilLedEn,
	_PhysicalIoName[47:59]:        BrakeLightEn,
	_PhysicalIoLowerName[47:59]:   BrakeLightEn,
	_PhysicalIoName[59:70]:        StatusLedEn,
	_PhysicalIoLowerName[59:70]:   StatusLedEn,
	_PhysicalIoName[70:76]:        RtdsEn,
	_PhysicalIoLowerName[70:76]:   RtdsEn,
	_PhysicalIoName[76:95]:        AccelPedalPosition1,
	_PhysicalIoLowerName[76:95]:   AccelPedalPosition1,
	_PhysicalIoName[95:114]:       AccelPedalPosition2,
	_PhysicalIoLowerName[95:114]:  AccelPedalPosition2,
	_PhysicalIoName[114:133]:      BrakePedalPosition1,
	_PhysicalIoLowerName[114:133]: BrakePedalPosition1,
	_PhysicalIoName[133:152]:      BrakePedalPosition2,
	_PhysicalIoLowerName[133:152]: BrakePedalPosition2,
	_PhysicalIoName[152:169]:      SuspensionTravel1,
	_PhysicalIoLowerName[152:169]: SuspensionTravel1,
	_PhysicalIoName[169:186]:      SuspensionTravel2,
	_PhysicalIoLowerName[169:186]: SuspensionTravel2,
	_PhysicalIoName[186:199]:      SteeringAngle,
	_PhysicalIoLowerName[186:199]: SteeringAngle,
	_PhysicalIoName[199:211]:      StartButtonN,
	_PhysicalIoLowerName[199:211]: StartButtonN,
	_PhysicalIoName[211:226]:      WheelSpeedLeftA,
	_PhysicalIoLowerName[211:226]: WheelSpeedLeftA,
	_PhysicalIoName[226:241]:      WheelSpeedLeftB,
	_PhysicalIoLowerName[226:241]: WheelSpeedLeftB,
	_PhysicalIoName[241:257]:      WheelSpeedRightA,
	_PhysicalIoLowerName[241:257]: WheelSpeedRightA,
	_PhysicalIoName[257:273]:      WheelSpeedRightB,
	_PhysicalIoLowerName[257:273]: WheelSpeedRightB,
	_PhysicalIoName[273:299]:      MotorControllerPrechargeEn,
	_PhysicalIoLowerName[273:299]: MotorControllerPrechargeEn,
	_PhysicalIoName[299:309]:      InverterEn,
	_PhysicalIoLowerName[299:309]: InverterEn,
	_PhysicalIoName[309:322]:      AccumulatorEn,
	_PhysicalIoLowerName[309:322]: AccumulatorEn,
	_PhysicalIoName[322:339]:      ShutdownCircuitEn,
	_PhysicalIoLowerName[322:339]: ShutdownCircuitEn,
	_PhysicalIoName[339:345]:      TsalEn,
	_PhysicalIoLowerName[339:345]: TsalEn,
	_PhysicalIoName[345:352]:      RaspiEn,
	_PhysicalIoLowerName[345:352]: RaspiEn,
	_PhysicalIoName[352:369]:      FrontControllerEn,
	_PhysicalIoLowerName[352:369]: FrontControllerEn,
	_PhysicalIoName[369:380]:      SpeedgoatEn,
	_PhysicalIoLowerName[369:380]: SpeedgoatEn,
	_PhysicalIoName[380:397]:      MotorControllerEn,
	_PhysicalIoLowerName[380:397]: MotorControllerEn,
	_PhysicalIoName[397:405]:      ImuGpsEn,
	_PhysicalIoLowerName[397:405]: ImuGpsEn,
	_PhysicalIoName[405:414]:      DcdcValid,
	_PhysicalIoLowerName[405:414]: DcdcValid,
	_PhysicalIoName[414:420]:      DcdcEn,
	_PhysicalIoLowerName[414:420]: DcdcEn,
	_PhysicalIoName[420:429]:      DcdcEnLed,
	_PhysicalIoLowerName[420:429]: DcdcEnLed,
	_PhysicalIoName[429:445]:      PowerTrainPumpEn,
	_PhysicalIoLowerName[429:445]: PowerTrainPumpEn,
	_PhysicalIoName[445:460]:      PowertrainFanEn,
	_PhysicalIoLowerName[445:460]: PowertrainFanEn,
	_PhysicalIoName[460:474]:      HvCurrentSense,
	_PhysicalIoLowerName[460:474]: HvCurrentSense,
	_PhysicalIoName[474:499]:      LvController3v3RefVoltage,
	_PhysicalIoLowerName[474:499]: LvController3v3RefVoltage,
	_PhysicalIoName[499:527]:      FrontController3v3RefVoltage,
	_PhysicalIoLowerName[499:527]: FrontController3v3RefVoltage,
	_PhysicalIoName[527:538]:      HvilDisable,
	_PhysicalIoLowerName[527:538]: HvilDisable,
	_PhysicalIoName[538:550]:      HvilFeedback,
	_PhysicalIoLowerName[538:550]: HvilFeedback,
	_PhysicalIoName[550:562]:      GlvmsDisable,
	_PhysicalIoLowerName[550:562]: GlvmsDisable,
	_PhysicalIoName[562:574]:      IndicatorLed,
	_PhysicalIoLowerName[562:574]: IndicatorLed,
	_PhysicalIoName[574:589]:      IndicatorButton,
	_PhysicalIoLowerName[574:589]: IndicatorButton,
}

var _PhysicalIoNames = []string{
	_PhysicalIoName[0:17],
	_PhysicalIoName[17:27],
	_PhysicalIoName[27:38],
	_PhysicalIoName[38:47],
	_PhysicalIoName[47:59],
	_PhysicalIoName[59:70],
	_PhysicalIoName[70:76],
	_PhysicalIoName[76:95],
	_PhysicalIoName[95:114],
	_PhysicalIoName[114:133],
	_PhysicalIoName[133:152],
	_PhysicalIoName[152:169],
	_PhysicalIoName[169:186],
	_PhysicalIoName[186:199],
	_PhysicalIoName[199:211],
	_PhysicalIoName[211:226],
	_PhysicalIoName[226:241],
	_PhysicalIoName[241:257],
	_PhysicalIoName[257:273],
	_PhysicalIoName[273:299],
	_PhysicalIoName[299:309],
	_PhysicalIoName[309:322],
	_PhysicalIoName[322:339],
	_PhysicalIoName[339:345],
	_PhysicalIoName[345:352],
	_PhysicalIoName[352:369],
	_PhysicalIoName[369:380],
	_PhysicalIoName[380:397],
	_PhysicalIoName[397:405],
	_PhysicalIoName[405:414],
	_PhysicalIoName[414:420],
	_PhysicalIoName[420:429],
	_PhysicalIoName[429:445],
	_PhysicalIoName[445:460],
	_PhysicalIoName[460:474],
	_PhysicalIoName[474:499],
	_PhysicalIoName[499:527],
	_PhysicalIoName[527:538],
	_PhysicalIoName[538:550],
	_PhysicalIoName[550:562],
	_PhysicalIoName[562:574],
	_PhysicalIoName[574:589],
}

// PhysicalIoString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PhysicalIoString(s string) (PhysicalIo, error) {
	if val, ok := _PhysicalIoNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PhysicalIoNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PhysicalIo values", s)
}

// PhysicalIoValues returns all values of the enum
func PhysicalIoValues() []PhysicalIo {
	return _PhysicalIoValues
}

// PhysicalIoStrings returns a slice of all String values of the enum
func PhysicalIoStrings() []string {
	strs := make([]string, len(_PhysicalIoNames))
	copy(strs, _PhysicalIoNames)
	return strs
}

// IsAPhysicalIo returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PhysicalIo) IsAPhysicalIo() bool {
	for _, v := range _PhysicalIoValues {
		if i == v {
			return true
		}
	}
	return false
}
