// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package signals

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Digital struct {
	_tab flatbuffers.Table
}

func GetRootAsDigital(buf []byte, offset flatbuffers.UOffsetT) *Digital {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Digital{}
	x.Init(buf, n+offset)
	return x
}

func FinishDigitalBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDigital(buf []byte, offset flatbuffers.UOffsetT) *Digital {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Digital{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDigitalBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Digital) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Digital) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Digital) Value() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Digital) MutateValue(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func DigitalStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func DigitalAddValue(builder *flatbuffers.Builder, value bool) {
	builder.PrependBoolSlot(0, value, false)
}
func DigitalEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
