// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package signals

import "strconv"

type SignalValue byte

const (
	SignalValueNONE    SignalValue = 0
	SignalValueDigital SignalValue = 1
	SignalValueAnalog  SignalValue = 2
)

var EnumNamesSignalValue = map[SignalValue]string{
	SignalValueNONE:    "NONE",
	SignalValueDigital: "Digital",
	SignalValueAnalog:  "Analog",
}

var EnumValuesSignalValue = map[string]SignalValue{
	"NONE":    SignalValueNONE,
	"Digital": SignalValueDigital,
	"Analog":  SignalValueAnalog,
}

func (v SignalValue) String() string {
	if s, ok := EnumNamesSignalValue[v]; ok {
		return s
	}
	return "SignalValue(" + strconv.FormatInt(int64(v), 10) + ")"
}
