revision: "sil"
canInterfaces:
  veh: "vcan0"
  pt: "vcan1"
traceDir: "../../macformula/results/traces"
logsDir: "../../macformula/results/logs"
reportsDir: "../../macformula/results/reports"
tagsFilePath: "../../../hil/macformula/config/tags.yaml"
canTracerTimeoutMinutes: 10
silPort: 9090