revision: "sil"
canInterfaces:
  veh: "vcan0"
  pt: "vcan1"
traceDir: "../../../traces"
logsDir: "../../../logs"
reportsDir: "../../../reports"
tagsFilePath: "../../../hil/macformula/config/tags.yaml"
historicTestsFilePath: "../../historic_tests.json"
canTracerTimeoutMinutes: 10
silPort: 9090