revision: "sil"
canInterfaces:
  veh: "vcan0"
  pt: "vcan1"
resultsDir: "/home/macformula/macfe/hil/macformula/test_results"
logsDir: "/home/macformula/macfe/hil/macformula/test_results/logs"
tagsFilePath: "/home/macformula/macfe/hil/macformula/config/tags.yaml"
canTracerTimeoutMinutes: 10
silPort: 9090