// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package signals

import "strconv"

type RequestType byte

const (
	RequestTypeNONE            RequestType = 0
	RequestTypeReadRequest     RequestType = 1
	RequestTypeSetRequest      RequestType = 2
	RequestTypeRegisterRequest RequestType = 3
)

var EnumNamesRequestType = map[RequestType]string{
	RequestTypeNONE:            "NONE",
	RequestTypeReadRequest:     "ReadRequest",
	RequestTypeSetRequest:      "SetRequest",
	RequestTypeRegisterRequest: "RegisterRequest",
}

var EnumValuesRequestType = map[string]RequestType{
	"NONE":            RequestTypeNONE,
	"ReadRequest":     RequestTypeReadRequest,
	"SetRequest":      RequestTypeSetRequest,
	"RegisterRequest": RequestTypeRegisterRequest,
}

func (v RequestType) String() string {
	if s, ok := EnumNamesRequestType[v]; ok {
		return s
	}
	return "RequestType(" + strconv.FormatInt(int64(v), 10) + ")"
}
