// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package signals

import "strconv"

type SIGNAL_DIRECTION int8

const (
	SIGNAL_DIRECTIONINPUT  SIGNAL_DIRECTION = 0
	SIGNAL_DIRECTIONOUTPUT SIGNAL_DIRECTION = 1
)

var EnumNamesSIGNAL_DIRECTION = map[SIGNAL_DIRECTION]string{
	SIGNAL_DIRECTIONINPUT:  "INPUT",
	SIGNAL_DIRECTIONOUTPUT: "OUTPUT",
}

var EnumValuesSIGNAL_DIRECTION = map[string]SIGNAL_DIRECTION{
	"INPUT":  SIGNAL_DIRECTIONINPUT,
	"OUTPUT": SIGNAL_DIRECTIONOUTPUT,
}

func (v SIGNAL_DIRECTION) String() string {
	if s, ok := EnumNamesSIGNAL_DIRECTION[v]; ok {
		return s
	}
	return "SIGNAL_DIRECTION(" + strconv.FormatInt(int64(v), 10) + ")"
}
