// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: lvcontroller.proto

package gotobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PWM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrequencyHz   float32                `protobuf:"fixed32,1,opt,name=frequency_hz,json=frequencyHz,proto3" json:"frequency_hz,omitempty"`
	DutyCycle     float32                `protobuf:"fixed32,2,opt,name=duty_cycle,json=dutyCycle,proto3" json:"duty_cycle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PWM) Reset() {
	*x = PWM{}
	mi := &file_lvcontroller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PWM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PWM) ProtoMessage() {}

func (x *PWM) ProtoReflect() protoreflect.Message {
	mi := &file_lvcontroller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PWM.ProtoReflect.Descriptor instead.
func (*PWM) Descriptor() ([]byte, []int) {
	return file_lvcontroller_proto_rawDescGZIP(), []int{0}
}

func (x *PWM) GetFrequencyHz() float32 {
	if x != nil {
		return x.FrequencyHz
	}
	return 0
}

func (x *PWM) GetDutyCycle() float32 {
	if x != nil {
		return x.DutyCycle
	}
	return 0
}

type Output struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tractive system status indicator
	TssiEn          bool `protobuf:"varint,1,opt,name=tssi_en,json=tssiEn,proto3" json:"tssi_en,omitempty"`
	TssiRedSignal   bool `protobuf:"varint,2,opt,name=tssi_red_signal,json=tssiRedSignal,proto3" json:"tssi_red_signal,omitempty"`
	TssiGreenSignal bool `protobuf:"varint,3,opt,name=tssi_green_signal,json=tssiGreenSignal,proto3" json:"tssi_green_signal,omitempty"`
	// Powertrain cooling
	PowertrainPump1En bool `protobuf:"varint,4,opt,name=powertrain_pump1_en,json=powertrainPump1En,proto3" json:"powertrain_pump1_en,omitempty"`
	PowertrainPump2En bool `protobuf:"varint,5,opt,name=powertrain_pump2_en,json=powertrainPump2En,proto3" json:"powertrain_pump2_en,omitempty"`
	PowertrainFan1En  bool `protobuf:"varint,6,opt,name=powertrain_fan1_en,json=powertrainFan1En,proto3" json:"powertrain_fan1_en,omitempty"`
	PowertrainFan2En  bool `protobuf:"varint,7,opt,name=powertrain_fan2_en,json=powertrainFan2En,proto3" json:"powertrain_fan2_en,omitempty"`
	PowertrainFanPwm  *PWM `protobuf:"bytes,8,opt,name=powertrain_fan_pwm,json=powertrainFanPwm,proto3" json:"powertrain_fan_pwm,omitempty"`
	// Motor Controller
	MotorControllerEn    bool `protobuf:"varint,9,opt,name=motor_controller_en,json=motorControllerEn,proto3" json:"motor_controller_en,omitempty"`
	MotorCtrlPrechargeEn bool `protobuf:"varint,10,opt,name=motor_ctrl_precharge_en,json=motorCtrlPrechargeEn,proto3" json:"motor_ctrl_precharge_en,omitempty"`
	MotorCtrlSwitchEn    bool `protobuf:"varint,11,opt,name=motor_ctrl_switch_en,json=motorCtrlSwitchEn,proto3" json:"motor_ctrl_switch_en,omitempty"`
	// Subsystems
	AccumulatorEn     bool `protobuf:"varint,12,opt,name=accumulator_en,json=accumulatorEn,proto3" json:"accumulator_en,omitempty"`
	FrontControllerEn bool `protobuf:"varint,13,opt,name=front_controller_en,json=frontControllerEn,proto3" json:"front_controller_en,omitempty"`
	ImuGpsEn          bool `protobuf:"varint,14,opt,name=imu_gps_en,json=imuGpsEn,proto3" json:"imu_gps_en,omitempty"`
	ShutdownCircuitEn bool `protobuf:"varint,15,opt,name=shutdown_circuit_en,json=shutdownCircuitEn,proto3" json:"shutdown_circuit_en,omitempty"`
	// DCDC System & measurement
	DcdcEn          bool `protobuf:"varint,16,opt,name=dcdc_en,json=dcdcEn,proto3" json:"dcdc_en,omitempty"`
	DcdcSenseSelect bool `protobuf:"varint,17,opt,name=dcdc_sense_select,json=dcdcSenseSelect,proto3" json:"dcdc_sense_select,omitempty"`
	// Other
	BrakeLightEn  bool `protobuf:"varint,18,opt,name=brake_light_en,json=brakeLightEn,proto3" json:"brake_light_en,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_lvcontroller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_lvcontroller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_lvcontroller_proto_rawDescGZIP(), []int{1}
}

func (x *Output) GetTssiEn() bool {
	if x != nil {
		return x.TssiEn
	}
	return false
}

func (x *Output) GetTssiRedSignal() bool {
	if x != nil {
		return x.TssiRedSignal
	}
	return false
}

func (x *Output) GetTssiGreenSignal() bool {
	if x != nil {
		return x.TssiGreenSignal
	}
	return false
}

func (x *Output) GetPowertrainPump1En() bool {
	if x != nil {
		return x.PowertrainPump1En
	}
	return false
}

func (x *Output) GetPowertrainPump2En() bool {
	if x != nil {
		return x.PowertrainPump2En
	}
	return false
}

func (x *Output) GetPowertrainFan1En() bool {
	if x != nil {
		return x.PowertrainFan1En
	}
	return false
}

func (x *Output) GetPowertrainFan2En() bool {
	if x != nil {
		return x.PowertrainFan2En
	}
	return false
}

func (x *Output) GetPowertrainFanPwm() *PWM {
	if x != nil {
		return x.PowertrainFanPwm
	}
	return nil
}

func (x *Output) GetMotorControllerEn() bool {
	if x != nil {
		return x.MotorControllerEn
	}
	return false
}

func (x *Output) GetMotorCtrlPrechargeEn() bool {
	if x != nil {
		return x.MotorCtrlPrechargeEn
	}
	return false
}

func (x *Output) GetMotorCtrlSwitchEn() bool {
	if x != nil {
		return x.MotorCtrlSwitchEn
	}
	return false
}

func (x *Output) GetAccumulatorEn() bool {
	if x != nil {
		return x.AccumulatorEn
	}
	return false
}

func (x *Output) GetFrontControllerEn() bool {
	if x != nil {
		return x.FrontControllerEn
	}
	return false
}

func (x *Output) GetImuGpsEn() bool {
	if x != nil {
		return x.ImuGpsEn
	}
	return false
}

func (x *Output) GetShutdownCircuitEn() bool {
	if x != nil {
		return x.ShutdownCircuitEn
	}
	return false
}

func (x *Output) GetDcdcEn() bool {
	if x != nil {
		return x.DcdcEn
	}
	return false
}

func (x *Output) GetDcdcSenseSelect() bool {
	if x != nil {
		return x.DcdcSenseSelect
	}
	return false
}

func (x *Output) GetBrakeLightEn() bool {
	if x != nil {
		return x.BrakeLightEn
	}
	return false
}

type Input struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tractive system status indicator
	ImdFault bool `protobuf:"varint,1,opt,name=imd_fault,json=imdFault,proto3" json:"imd_fault,omitempty"`
	BmsFault bool `protobuf:"varint,2,opt,name=bms_fault,json=bmsFault,proto3" json:"bms_fault,omitempty"`
	// DCDC System & Measurement
	DcdcSense         float32 `protobuf:"fixed32,3,opt,name=dcdc_sense,json=dcdcSense,proto3" json:"dcdc_sense,omitempty"`
	SuspensionTravel3 float32 `protobuf:"fixed32,4,opt,name=suspension_travel3,json=suspensionTravel3,proto3" json:"suspension_travel3,omitempty"`
	SuspensionTravel4 float32 `protobuf:"fixed32,5,opt,name=suspension_travel4,json=suspensionTravel4,proto3" json:"suspension_travel4,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_lvcontroller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_lvcontroller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_lvcontroller_proto_rawDescGZIP(), []int{2}
}

func (x *Input) GetImdFault() bool {
	if x != nil {
		return x.ImdFault
	}
	return false
}

func (x *Input) GetBmsFault() bool {
	if x != nil {
		return x.BmsFault
	}
	return false
}

func (x *Input) GetDcdcSense() float32 {
	if x != nil {
		return x.DcdcSense
	}
	return 0
}

func (x *Input) GetSuspensionTravel3() float32 {
	if x != nil {
		return x.SuspensionTravel3
	}
	return 0
}

func (x *Input) GetSuspensionTravel4() float32 {
	if x != nil {
		return x.SuspensionTravel4
	}
	return 0
}

var File_lvcontroller_proto protoreflect.FileDescriptor

const file_lvcontroller_proto_rawDesc = "" +
	"\n" +
	"\x12lvcontroller.proto\x12\flvcontroller\"G\n" +
	"\x03PWM\x12!\n" +
	"\ffrequency_hz\x18\x01 \x01(\x02R\vfrequencyHz\x12\x1d\n" +
	"\n" +
	"duty_cycle\x18\x02 \x01(\x02R\tdutyCycle\"\x9a\x06\n" +
	"\x06Output\x12\x17\n" +
	"\atssi_en\x18\x01 \x01(\bR\x06tssiEn\x12&\n" +
	"\x0ftssi_red_signal\x18\x02 \x01(\bR\rtssiRedSignal\x12*\n" +
	"\x11tssi_green_signal\x18\x03 \x01(\bR\x0ftssiGreenSignal\x12.\n" +
	"\x13powertrain_pump1_en\x18\x04 \x01(\bR\x11powertrainPump1En\x12.\n" +
	"\x13powertrain_pump2_en\x18\x05 \x01(\bR\x11powertrainPump2En\x12,\n" +
	"\x12powertrain_fan1_en\x18\x06 \x01(\bR\x10powertrainFan1En\x12,\n" +
	"\x12powertrain_fan2_en\x18\a \x01(\bR\x10powertrainFan2En\x12?\n" +
	"\x12powertrain_fan_pwm\x18\b \x01(\v2\x11.lvcontroller.PWMR\x10powertrainFanPwm\x12.\n" +
	"\x13motor_controller_en\x18\t \x01(\bR\x11motorControllerEn\x125\n" +
	"\x17motor_ctrl_precharge_en\x18\n" +
	" \x01(\bR\x14motorCtrlPrechargeEn\x12/\n" +
	"\x14motor_ctrl_switch_en\x18\v \x01(\bR\x11motorCtrlSwitchEn\x12%\n" +
	"\x0eaccumulator_en\x18\f \x01(\bR\raccumulatorEn\x12.\n" +
	"\x13front_controller_en\x18\r \x01(\bR\x11frontControllerEn\x12\x1c\n" +
	"\n" +
	"imu_gps_en\x18\x0e \x01(\bR\bimuGpsEn\x12.\n" +
	"\x13shutdown_circuit_en\x18\x0f \x01(\bR\x11shutdownCircuitEn\x12\x17\n" +
	"\adcdc_en\x18\x10 \x01(\bR\x06dcdcEn\x12*\n" +
	"\x11dcdc_sense_select\x18\x11 \x01(\bR\x0fdcdcSenseSelect\x12$\n" +
	"\x0ebrake_light_en\x18\x12 \x01(\bR\fbrakeLightEn\"\xbe\x01\n" +
	"\x05Input\x12\x1b\n" +
	"\timd_fault\x18\x01 \x01(\bR\bimdFault\x12\x1b\n" +
	"\tbms_fault\x18\x02 \x01(\bR\bbmsFault\x12\x1d\n" +
	"\n" +
	"dcdc_sense\x18\x03 \x01(\x02R\tdcdcSense\x12-\n" +
	"\x12suspension_travel3\x18\x04 \x01(\x02R\x11suspensionTravel3\x12-\n" +
	"\x12suspension_travel4\x18\x05 \x01(\x02R\x11suspensionTravel4B\vZ\t./gotobufb\x06proto3"

var (
	file_lvcontroller_proto_rawDescOnce sync.Once
	file_lvcontroller_proto_rawDescData []byte
)

func file_lvcontroller_proto_rawDescGZIP() []byte {
	file_lvcontroller_proto_rawDescOnce.Do(func() {
		file_lvcontroller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lvcontroller_proto_rawDesc), len(file_lvcontroller_proto_rawDesc)))
	})
	return file_lvcontroller_proto_rawDescData
}

var file_lvcontroller_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lvcontroller_proto_goTypes = []any{
	(*PWM)(nil),    // 0: lvcontroller.PWM
	(*Output)(nil), // 1: lvcontroller.Output
	(*Input)(nil),  // 2: lvcontroller.Input
}
var file_lvcontroller_proto_depIdxs = []int32{
	0, // 0: lvcontroller.Output.powertrain_fan_pwm:type_name -> lvcontroller.PWM
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lvcontroller_proto_init() }
func file_lvcontroller_proto_init() {
	if File_lvcontroller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lvcontroller_proto_rawDesc), len(file_lvcontroller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lvcontroller_proto_goTypes,
		DependencyIndexes: file_lvcontroller_proto_depIdxs,
		MessageInfos:      file_lvcontroller_proto_msgTypes,
	}.Build()
	File_lvcontroller_proto = out.File
	file_lvcontroller_proto_goTypes = nil
	file_lvcontroller_proto_depIdxs = nil
}
