// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package signals

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Analog struct {
	_tab flatbuffers.Table
}

func GetRootAsAnalog(buf []byte, offset flatbuffers.UOffsetT) *Analog {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Analog{}
	x.Init(buf, n+offset)
	return x
}

func FinishAnalogBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAnalog(buf []byte, offset flatbuffers.UOffsetT) *Analog {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Analog{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAnalogBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Analog) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Analog) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Analog) Voltage() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Analog) MutateVoltage(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

func AnalogStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AnalogAddVoltage(builder *flatbuffers.Builder, voltage float64) {
	builder.PrependFloat64Slot(0, voltage, 0.0)
}
func AnalogEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
