// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package signals

import "strconv"

type ResponseType byte

const (
	ResponseTypeNONE         ResponseType = 0
	ResponseTypeReadResponse ResponseType = 1
	ResponseTypeSetResponse  ResponseType = 2
)

var EnumNamesResponseType = map[ResponseType]string{
	ResponseTypeNONE:         "NONE",
	ResponseTypeReadResponse: "ReadResponse",
	ResponseTypeSetResponse:  "SetResponse",
}

var EnumValuesResponseType = map[string]ResponseType{
	"NONE":         ResponseTypeNONE,
	"ReadResponse": ResponseTypeReadResponse,
	"SetResponse":  ResponseTypeSetResponse,
}

func (v ResponseType) String() string {
	if s, ok := EnumNamesResponseType[v]; ok {
		return s
	}
	return "ResponseType(" + strconv.FormatInt(int64(v), 10) + ")"
}
