// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package signals

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SetResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsSetResponse(buf []byte, offset flatbuffers.UOffsetT) *SetResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SetResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishSetResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSetResponse(buf []byte, offset flatbuffers.UOffsetT) *SetResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SetResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSetResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SetResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SetResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SetResponse) Ok() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return true
}

func (rcv *SetResponse) MutateOk(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *SetResponse) Error() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func SetResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SetResponseAddOk(builder *flatbuffers.Builder, ok bool) {
	builder.PrependBoolSlot(0, ok, true)
}
func SetResponseAddError(builder *flatbuffers.Builder, error flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(error), 0)
}
func SetResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
