// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package signals

import "strconv"

type SIGNAL_TYPE int8

const (
	SIGNAL_TYPEDIGITAL SIGNAL_TYPE = 0
	SIGNAL_TYPEANALOG  SIGNAL_TYPE = 1
)

var EnumNamesSIGNAL_TYPE = map[SIGNAL_TYPE]string{
	SIGNAL_TYPEDIGITAL: "DIGITAL",
	SIGNAL_TYPEANALOG:  "ANALOG",
}

var EnumValuesSIGNAL_TYPE = map[string]SIGNAL_TYPE{
	"DIGITAL": SIGNAL_TYPEDIGITAL,
	"ANALOG":  SIGNAL_TYPEANALOG,
}

func (v SIGNAL_TYPE) String() string {
	if s, ok := EnumNamesSIGNAL_TYPE[v]; ok {
		return s
	}
	return "SIGNAL_TYPE(" + strconv.FormatInt(int64(v), 10) + ")"
}
